"use client";

import Image from "next/image";
import { FormEvent, useMemo, useState } from "react";
import { ArrowDown, ArrowRight, Bot, BrainCircuit, Camera, ChevronRight, CircleDot, Cpu, ExternalLink, FileText, Gauge, Languages, Mail, Menu, MessageCircle, Pause, Radio, ScanLine, ShieldCheck, Volume2, Waves, X, ZoomIn } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";

type Locale = "pt" | "en" | "es";
type Version = "v1" | "v2" | "v3";

const status = {
  v1: { pt: "Validado fisicamente", en: "Physically validated", es: "Validado físicamente" },
  v2: { pt: "Validado fisicamente", en: "Physically validated", es: "Validado físicamente" },
  v3: { pt: "Em construção", en: "Under construction", es: "En construcción" },
};

const gallery = [
  { src: "/assets/v2-prototipo-01.jpg", version: "v2", category: "mecânica", title: "HydroBot V2 — vista lateral", detail: "Protótipo funcional sobre a base Max Bombeiro." },
  { src: "/assets/v2-prototipo-02.jpg", version: "v2", category: "mecânica", title: "HydroBot V2 — vista frontal", detail: "Estrutura física e integração do protótipo de 2025." },
  { src: "/assets/v2-equipe-construcao.jpg", version: "v2", category: "processo", title: "Construção da V2", detail: "Registro da equipe durante a montagem do protótipo." },
  { src: "/assets/v2-apresentacao.jpg", version: "v2", category: "eventos", title: "Apresentação pública", detail: "Demonstração do HydroBot V2 em evento técnico." },
  { src: "/assets/v1-diagrama-tinkercad.png", version: "v1", category: "elétrica", title: "Diagrama eletrônico da V1", detail: "Modelo do circuito produzido pela equipe no Tinkercad." },
  { src: "/assets/v1-diagrama-comportamento.png", version: "v1", category: "software", title: "Comportamento da V1", detail: "Fluxo de detecção, aproximação e acionamento hidráulico." },
  { src: "/assets/v3-desenho-montagem.webp", version: "v3", category: "desenho técnico", title: "Montagem provisória da V3", detail: "Prancha 01/09 do detalhamento mecânico: visão geral, dimensões e organização dos principais módulos." },
  { src: "/assets/v3-desenho-base-torre.webp", version: "v3", category: "desenho técnico", title: "Base da torre", detail: "Prancha 04/09 com vistas, cortes, furações e dimensões da base da torre." },
  { src: "/assets/v3-desenho-base-tanque.webp", version: "v3", category: "desenho técnico", title: "Base do tanque", detail: "Prancha 05/09 com detalhamento dimensional da estrutura externa do tanque." },
  { src: "/assets/v3-desenho-base-cabeca.webp", version: "v3", category: "desenho técnico", title: "Base da cabeça", detail: "Prancha 06/09 com vistas e dimensões do módulo frontal da V3." },
] as const;

const timeline = [
  ["25.10.2024", "Casa Aberta ETEC — primeira apresentação", "V1"],
  ["24.03.2025", "Arduino Day FATEC Bauru", "V1"],
  ["30.09.2025", "Reportagem BG Interior / Record Paulista", "V2"],
  ["02.10.2025", "16ª FETEPS — avaliação por banca técnica", "V2"],
  ["02.10.2025", "Expo Jovem Avaí — data a confirmar", "V2"],
  ["03.10.2025", "Reportagem BG SP / Balanço Geral", "V2"],
  ["31.10.2025", "Casa Aberta ETEC — HydroBot 2.0", "V2"],
  ["08.11.2025", "EcoEsquema", "V2"],
  ["2026", "Projeto Integrador FATEC + Inova CPS", "V3"],
];

function StatusBadge({ version, locale }: { version: Version; locale: Locale }) {
  return <span className={`status status-${version}`}><span className="status-dot" />{status[version][locale]}</span>;
}

function SectionTitle({ eyebrow, title, body }: { eyebrow: string; title: string; body?: string }) {
  return <div className="section-title"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{body && <p>{body}</p>}</div>;
}

export default function Home() {
  const [locale, setLocale] = useState<Locale>("pt");
  const [version, setVersion] = useState<Version>("v3");
  const [galleryFilter, setGalleryFilter] = useState<"all" | Version>("all");
  const [selectedImage, setSelectedImage] = useState<(typeof gallery)[number] | null>(null);
  const [question, setQuestion] = useState("");
  const [messages, setMessages] = useState<{ role: "user" | "bot"; text: string }[]>([]);
  const [sending, setSending] = useState(false);
  const [speaking, setSpeaking] = useState(false);
  const [mobileOpen, setMobileOpen] = useState(false);
  const tr = (pt: string, en: string, es: string) => ({ pt, en, es }[locale]);
  const filteredGallery = useMemo(() => gallery.filter((item) => galleryFilter === "all" || item.version === galleryFilter), [galleryFilter]);

  const nav = [["evolucao", tr("Evolução", "Evolution", "Evolución")], ["v3", "V3 + IA"], ["galeria", tr("Galeria", "Gallery", "Galería")], ["trajetoria", tr("Trajetória", "Journey", "Trayectoria")], ["equipe", tr("Equipe", "Team", "Equipo")]];

  const speak = () => {
    if (speaking) { speechSynthesis.cancel(); setSpeaking(false); return; }
    const utterance = new SpeechSynthesisUtterance((document.querySelector("main")?.textContent ?? "").slice(0, 12000));
    utterance.lang = locale === "pt" ? "pt-BR" : locale === "en" ? "en-US" : "es-ES";
    utterance.rate = 0.96; utterance.onend = () => setSpeaking(false);
    speechSynthesis.cancel(); speechSynthesis.speak(utterance); setSpeaking(true);
  };

  const answerQuestion = (value: string) => {
    const q = value.toLowerCase();
    if (q.includes("ia") || q.includes("ai") || q.includes("inteligencia")) return tr("Na V3, a câmera térmica alimenta um modelo ONNX no Raspberry Pi 5. A posição detectada orienta o pan/tilt da torre, mas o disparo sempre passa pelos intertravamentos de segurança.", "In V3, the thermal camera feeds an ONNX model on the Raspberry Pi 5. The detected position guides the turret pan/tilt, while firing always passes through safety interlocks.", "En la V3, la cámara térmica alimenta un modelo ONNX en la Raspberry Pi 5. La posición detectada guía el pan/tilt de la torre, pero el disparo siempre pasa por interbloqueos de seguridad.");
    if (q.includes("v1") || q.includes("2024")) return tr("A V1 foi a prova de conceito com Arduino Uno, sensor de chama, quatro motores, servo MG90S e reservatório de 50 mL.", "V1 was the proof of concept with Arduino Uno, flame sensor, four motors, MG90S servo and a 50 mL tank.", "La V1 fue la prueba de concepto con Arduino Uno, sensor de llama, cuatro motores, servo MG90S y depósito de 50 mL.");
    if (q.includes("v2") || q.includes("2025")) return tr("A V2 corresponde ao projeto entregue como TCC: ESP32-S3 UNO, dois sensores KY-026, bomba JT-100, tração diferencial e app React Native. Os registros da FETEPS ainda mostram a configuração anterior com ESP32-CAM.", "V2 corresponds to the final course project: ESP32-S3 UNO, two KY-026 sensors, JT-100 pump, differential drive and a React Native app. FETEPS records still show the earlier ESP32-CAM configuration.", "La V2 corresponde al proyecto final: ESP32-S3 UNO, dos sensores KY-026, bomba JT-100, tracción diferencial y app React Native. Los registros de FETEPS todavía muestran la configuración anterior con ESP32-CAM.");
    if (q.includes("pront") || q.includes("status") || q.includes("ready")) return tr("V1 e V2 foram validadas fisicamente. A V3 está em construção: arquitetura e decisões principais estão documentadas, mas benchmarks e testes reais ainda precisam ser concluídos.", "V1 and V2 were physically validated. V3 is under construction: architecture and main decisions are documented, but benchmarks and physical tests are still pending.", "V1 y V2 fueron validadas físicamente. La V3 está en construcción: la arquitectura y las decisiones principales están documentadas, pero faltan benchmarks y pruebas físicas.");
    return tr("Posso explicar as versões, componentes, IA, segurança ou trajetória. Tente: “como funciona a IA da V3?”", "I can explain versions, components, AI, safety or the journey. Try: “how does V3 AI work?”", "Puedo explicar versiones, componentes, IA, seguridad o trayectoria. Prueba: “¿cómo funciona la IA de la V3?”");
  };

  const sendQuestion = async (event: FormEvent) => {
    event.preventDefault(); const value = question.trim(); if (!value || sending) return;
    const answer = answerQuestion(value); setMessages((m) => [...m, { role: "user", text: value }, { role: "bot", text: answer }]); setQuestion(""); setSending(true);
    try { await fetch("/api/questions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question: value, answer, locale }) }); } finally { setSending(false); }
  };

  const versions = {
    v1: { year: "2024", title: tr("Prova de conceito", "Proof of concept", "Prueba de concepto"), body: tr("O primeiro robô validou o ciclo essencial: detectar, mover, apontar e bombear água. A documentação confirma a configuração real, sem completar lacunas por suposição.", "The first robot validated the essential cycle: detect, move, aim and pump water. Documentation confirms its actual configuration without assumptions.", "El primer robot validó el ciclo esencial: detectar, mover, apuntar y bombear agua. La documentación confirma su configuración real sin suposiciones."), chips: ["Arduino Uno", "MG90S", "4× motor DC", "L298N", "KWC-130CH", "50 mL"] },
    v2: { year: "2025", title: tr("Protótipo funcional — TCC", "Functional prototype — final project", "Prototipo funcional — proyecto final"), body: tr("A V2 é o projeto entregue como TCC. Na fase apresentada à FETEPS, os registros mostram ESP32-CAM; após o evento, a documentação registra a transição para ESP32-S3 UNO. A base Max Bombeiro recebeu dois sensores de chama, sensor de nível, tração diferencial, spray PWM e aplicativo React Native.", "V2 is the final course project. FETEPS records show the ESP32-CAM configuration; after the event, the documentation records the transition to ESP32-S3 UNO. The Max Bombeiro base received two flame sensors, a level sensor, differential drive, PWM spray and a React Native app.", "La V2 es el proyecto final. Los registros de FETEPS muestran la configuración con ESP32-CAM; después del evento, la documentación registra la transición a ESP32-S3 UNO. La base Max Bombeiro recibió dos sensores de llama, sensor de nivel, tracción diferencial, spray PWM y app React Native."), chips: ["ESP32-S3 UNO", "ESP32-CAM", "2× KY-026", "JT-100", "FD-10", "React Native"] },
    v3: { year: "2026", title: tr("Plataforma com IA embarcada", "Embedded AI platform", "Plataforma con IA embarcada"), body: tr("A nova arquitetura troca remendos por módulos testáveis: 4×4, três circuitos hidráulicos, percepção térmica, SLAM 2D e processamento local no Raspberry Pi 5. O aplicativo da V3 utiliza React Native para a interface móvel, TypeScript como linguagem e Expo como plataforma de desenvolvimento e geração do aplicativo.", "The new architecture replaces patches with testable modules: 4×4, three hydraulic circuits, thermal perception, 2D SLAM and local processing on Raspberry Pi 5. The V3 app uses React Native for the mobile interface, TypeScript as its language and Expo as the development and app-building platform.", "La nueva arquitectura sustituye parches por módulos comprobables: 4×4, tres circuitos hidráulicos, percepción térmica, SLAM 2D y procesamiento local en Raspberry Pi 5. La aplicación de la V3 utiliza React Native para la interfaz móvil, TypeScript como lenguaje y Expo como plataforma de desarrollo y generación de la aplicación."), chips: ["Raspberry Pi 5", "ROS 2 Jazzy", "ONNX Runtime", "LiDAR 2D", "MQTT", "React Native", "TypeScript", "Expo"] },
  };

  return <main id="top">
    <header className="site-header">
      <a className="brand" href="#top"><Image src="/assets/hydrobot-logo.png" alt="Logo HydroBot" width={48} height={48} priority /><span><b>HYDRO</b>BOT<small>ENGINEERING LOG</small></span></a>
      <nav className="desktop-nav">{nav.map(([id, label]) => <a key={id} href={`#${id}`}>{label}</a>)}</nav>
      <div className="header-actions"><button className="icon-button" onClick={speak} aria-label={speaking ? "Parar leitura" : "Ouvir página"}>{speaking ? <Pause /> : <Volume2 />}</button><label className="locale-select"><Languages /><span className="sr-only">Idioma</span><select value={locale} onChange={(e) => setLocale(e.target.value as Locale)}><option value="pt">PT</option><option value="en">EN</option><option value="es">ES</option></select></label><button className="menu-button" onClick={() => setMobileOpen(!mobileOpen)} aria-label="Menu" aria-expanded={mobileOpen} aria-controls="mobile-navigation">{mobileOpen ? <X /> : <Menu />}</button></div>
      {mobileOpen && <nav className="mobile-nav" id="mobile-navigation">{nav.map(([id, label]) => <a key={id} href={`#${id}`} onClick={() => setMobileOpen(false)}>{label}</a>)}</nav>}
    </header>

    <section className="hero"><div className="hero-grid" />
      <div className="hero-copy"><p className="eyebrow"><span className="live-dot" />{tr("Portfólio de engenharia · 2024—2026", "Engineering portfolio · 2024—2026", "Portafolio de ingeniería · 2024—2026")}</p><h1>{tr("Do protótipo escolar à", "From school prototype to", "Del prototipo escolar a la")} <span>{tr("IA embarcada.", "embedded AI.", "IA embarcada.")}</span></h1><p className="hero-lead">{tr("Três versões. Uma evolução documentada. O HydroBot tornou-se uma plataforma robótica modular para resposta inicial a incêndios — com transparência sobre o que já foi validado e o que ainda está sendo construído.", "Three versions. One documented evolution. HydroBot became a modular robotic platform for initial fire response—with clear boundaries between what is validated and what is still being built.", "Tres versiones. Una evolución documentada. HydroBot se convirtió en una plataforma robótica modular para respuesta inicial a incendios, diferenciando lo validado de lo que aún está en construcción.")}</p><div className="hero-actions"><a className="primary-button" href="#evolucao">{tr("Explorar evolução", "Explore evolution", "Explorar evolución")} <ArrowDown /></a><a className="ghost-button" href="#ia">{tr("Ver arquitetura de IA", "View AI architecture", "Ver arquitectura de IA")} <ArrowRight /></a></div><div className="hero-statuses">{(["v1", "v2", "v3"] as Version[]).map((v, i) => <div key={v}><span>{v.toUpperCase()} · {2024 + i}</span><StatusBadge version={v} locale={locale} /></div>)}</div></div>
      <div className="hero-visual"><div className="hero-photo-wrap"><Image src="/assets/v2-prototipo-01.jpg" alt="HydroBot V2" fill sizes="(max-width:900px) 100vw,44vw" priority /><div className="scan-line" /><div className="target target-a"><span /></div><div className="target target-b"><span /></div><span className="visual-label label-top">VISUAL / V2</span><span className="visual-label label-bottom">DOCUMENTED HARDWARE</span></div><div className="hero-specs"><div><small>{tr("Detecção V3", "V3 detection", "Detección V3")}</small><b>{tr("Térmica + IA", "Thermal + AI", "Térmica + IA")}</b></div><div><small>{tr("Processamento", "Compute", "Procesamiento")}</small><b>Raspberry Pi 5</b></div><div><small>{tr("Operação", "Operation", "Operación")}</small><b>Local-first</b></div></div></div>
    </section>

    <section className="evolution" id="evolucao"><SectionTitle eyebrow={tr("Evolução técnica", "Technical evolution", "Evolución técnica")} title={tr("Cada problema virou requisito.", "Every problem became a requirement.", "Cada problema se convirtió en requisito.")} body={tr("A história não esconde falhas: elas explicam por que a arquitetura mudou.", "The story does not hide failures: they explain why the architecture changed.", "La historia no oculta fallos: explican por qué cambió la arquitectura.")} />
      <div className="version-tabs">{(["v1", "v2", "v3"] as Version[]).map((item) => <button key={item} aria-selected={version === item} onClick={() => setVersion(item)}><b>{item.toUpperCase()}</b><span>{versions[item].year}</span></button>)}</div>
      <div className="version-panel"><div className="version-summary"><div className="version-index">{version.toUpperCase()}<span> / {versions[version].year}</span></div><StatusBadge version={version} locale={locale} /><h3>{versions[version].title}</h3><p>{versions[version].body}</p><div className="chip-list">{versions[version].chips.map((chip) => <span key={chip}>{chip}</span>)}</div></div>
        {version === "v1" && <div className="version-detail"><h4>{tr("O que a V1 ensinou", "What V1 taught", "Lo que enseñó la V1")}</h4><ul><li>{tr("Corrente insuficiente impedia o uso correto da ponte H.", "Insufficient current prevented proper H-bridge use.", "La corriente insuficiente impedía usar el puente H.")}</li><li>{tr("Vazamentos no spray ameaçavam servo e sensores.", "Spray leaks threatened the servo and sensors.", "Las fugas amenazaban el servo y los sensores.")}</li><li>{tr("A autonomia caía rapidamente sem fonte externa.", "Runtime dropped quickly without an external source.", "La autonomía caía sin fuente externa.")}</li></ul><Image src="/assets/v1-diagrama-comportamento.png" alt="Diagrama V1" width={808} height={467} /></div>}
        {version === "v2" && <div className="version-detail spec-grid"><div><small>RFH01</small><b>{tr("Detectar chama ≥ 40 cm", "Detect flame ≥ 40 cm", "Detectar llama ≥ 40 cm")}</b></div><div><small>RFH02</small><b>{tr("Navegar em corredores ≈ 40 cm", "Navigate ≈ 40 cm corridors", "Navegar pasillos ≈ 40 cm")}</b></div><div><small>RFH03</small><b>{tr("Acionar spray com limite", "Activate spray with limit", "Activar spray con límite")}</b></div><div><small>RFH04</small><b>{tr("Monitorar água/bateria", "Monitor water/battery", "Monitorear agua/batería")}</b></div></div>}
        {version === "v3" && <div className="version-detail modules-mini"><div><Cpu /><span><b>ROS 2 Jazzy</b><small>Ubuntu 24.04 LTS</small></span></div><div><Waves /><span><b>{tr("Hidráulica tripla", "Triple hydraulics", "Hidráulica triple")}</b><small>Torre · shield · sprinkler</small></span></div><div><ShieldCheck /><span><b>{tr("Segurança", "Safety", "Seguridad")}</b><small>Watchdog + interlocks</small></span></div><div><ScanLine /><span><b>SLAM 2D</b><small>LiDAR + Nav2</small></span></div></div>}
      </div>
    </section>

    <section className="bridge-section" id="v2"><SectionTitle eyebrow="V2 → V3" title={tr("Limitações comprovadas. Respostas projetadas.", "Proven limitations. Designed responses.", "Limitaciones comprobadas. Respuestas diseñadas.")} /><div className="problem-table">{[[tr("Sensores de chama instáveis", "Unstable flame sensors", "Sensores inestables"), tr("Câmera térmica + IA", "Thermal camera + AI", "Cámara térmica + IA")],[tr("Pressão imprecisa", "Imprecise pressure", "Presión imprecisa"),tr("Três circuitos hidráulicos", "Three hydraulic circuits", "Tres circuitos hidráulicos")],[tr("Rodas desniveladas", "Uneven wheels", "Ruedas desniveladas"),tr("Base 4×4 com suspensão", "4×4 base with suspension", "Base 4×4 con suspensión")],[tr("ESP32-CAM sobrecarregado", "Overloaded ESP32-CAM", "ESP32-CAM sobrecargado"),"Raspberry Pi 5 + ONNX Runtime"],[tr("Telemetria inconsistente", "Inconsistent telemetry", "Telemetría inconsistente"),"MQTT versionado + JSON"],[tr("Falhas de energia", "Power failures", "Fallos de energía"),tr("Power budget + fusíveis", "Power budget + fuses", "Power budget + fusibles")]].map(([problem,response],i)=><div className="problem-row" key={problem}><span className="problem-number">0{i+1}</span><div><small>V2 / {tr("problema","problem","problema")}</small><b>{problem}</b></div><ChevronRight/><div><small>V3 / {tr("resposta","response","respuesta")}</small><b>{response}</b></div></div>)}</div></section>

    <section className="v3-section" id="v3"><div className="v3-intro"><div><p className="eyebrow">V3 · 2026 / SYSTEM BLUEPRINT</p><h2>{tr("Uma plataforma modular, não apenas um carrinho.", "A modular platform, not just a vehicle.", "Una plataforma modular, no solo un vehículo.")}</h2></div><div className="v3-status"><StatusBadge version="v3" locale={locale}/><p>{tr("Arquitetura e desenho mecânico documentados. Fabricação e validação física em andamento.", "Architecture and mechanical design documented. Fabrication and physical validation in progress.", "Arquitectura y diseño mecánico documentados. Fabricación y validación física en curso.")}</p></div></div><div className="module-grid">{[[Gauge,tr("Mecânica 4×4","4×4 mechanics","Mecánica 4×4"),tr("Direção dianteira, suspensão funcional, tanque central e eletrônica na zona seca.","Front steering, functional suspension, central tank and electronics in the dry zone.","Dirección delantera, suspensión funcional, tanque central y electrónica en zona seca.")],[Waves,tr("Hidráulica tripla","Triple hydraulics","Hidráulica triple"),tr("Bombas independentes para torre, shield e sprinkler frontal.","Independent pumps for turret, shield and front sprinkler.","Bombas independientes para torre, shield y sprinkler frontal.")],[Camera,tr("Percepção","Perception","Percepción"),tr("Câmeras térmica e RGB, LiDAR 2D, IMU, encoders e sensores térmicos.","Thermal and RGB cameras, 2D LiDAR, IMU, encoders and thermal sensors.","Cámaras térmica y RGB, LiDAR 2D, IMU, encoders y sensores térmicos.")],[Radio,tr("Comunicação","Communication","Comunicación"),tr("MQTT, WebRTC e operação local-first.","MQTT, WebRTC and local-first operation.","MQTT, WebRTC y operación local-first.")]].map(([Icon,title,body])=>{const I=Icon as typeof Gauge;return <article className="module-card" key={String(title)}><I/><span className="module-status">{tr("Em projeto","In design","En proyecto")}</span><h3>{String(title)}</h3><p>{String(body)}</p></article>})}</div>
      <div className="technical-blueprints"><button className="technical-blueprint-preview" onClick={()=>setSelectedImage(gallery[6])} aria-label={tr("Ampliar desenho técnico da montagem V3","Enlarge V3 assembly drawing","Ampliar dibujo técnico del montaje V3")}><Image src="/assets/v3-desenho-montagem.webp" alt={tr("Desenho técnico da montagem provisória do HydroBot V3","Technical drawing of the provisional HydroBot V3 assembly","Dibujo técnico del montaje provisional del HydroBot V3")} fill sizes="(max-width:900px) 100vw,58vw"/><span><ZoomIn/> 01 / 09</span></button><div className="technical-blueprint-copy"><p className="eyebrow">V3 / {tr("ENGENHARIA MECÂNICA","MECHANICAL ENGINEERING","INGENIERÍA MECÁNICA")}</p><h3>{tr("Do conceito ao detalhamento.","From concept to detailing.","Del concepto al detalle.")}</h3><p>{tr("O caderno técnico registra a montagem provisória e o detalhamento dimensional das principais peças da estrutura. Ele comprova o avanço do projeto, mas não representa uma V3 fisicamente validada.","The technical booklet records the provisional assembly and dimensional detailing of the main structural parts. It demonstrates project progress, but does not represent a physically validated V3.","El cuaderno técnico registra el montaje provisional y el detalle dimensional de las principales piezas estructurales. Demuestra el avance del proyecto, pero no representa una V3 validada físicamente.")}</p><div className="technical-meta"><span>Autodesk Inventor 2025</span><span>9 {tr("pranchas A3","A3 sheets","láminas A3")}</span><span>{tr("Atualizado em 05/10/2026","Updated Oct 5, 2026","Actualizado el 05/10/2026")}</span></div><a className="blueprint-link" href="https://drive.google.com/file/d/1pMhLYiifPnL_NnEQex6v8ombj0InppYx/view" target="_blank" rel="noreferrer"><FileText/>{tr("Abrir caderno técnico completo","Open complete technical booklet","Abrir cuaderno técnico completo")}<ExternalLink/></a></div></div>
    </section>

    <section className="ai-section" id="ia"><div className="ai-heading"><div><p className="eyebrow">V3 / EMBEDDED AI</p><h2>{tr("A IA detecta. A torre alinha. A segurança autoriza.","AI detects. The turret aligns. Safety authorizes.","La IA detecta. La torre alinea. La seguridad autoriza.")}</h2></div><p>{tr("Nenhuma função crítica depende de internet. A variante final do modelo só será escolhida após benchmark com SLAM, streaming e controle simultâneos.","No critical function depends on the internet. The final model will only be selected after benchmarking with simultaneous SLAM, streaming and control.","Ninguna función crítica depende de internet. El modelo final se elegirá tras un benchmark con SLAM, streaming y control simultáneos.")}</p></div>
      <div className="pipeline"><div className="pipeline-node"><Camera/><small>01 / INPUT</small><b>{tr("Câmera térmica","Thermal camera","Cámara térmica")}</b><span>{tr("Assinatura térmica","Thermal signature","Firma térmica")}</span></div><ArrowRight/><div className="pipeline-node"><ScanLine/><small>02 / VISION</small><b>OpenCV</b><span>{tr("Pré-processamento","Pre-processing","Preprocesamiento")}</span></div><ArrowRight/><div className="pipeline-node active"><BrainCircuit/><small>03 / INFERENCE</small><b>ONNX Runtime</b><span>Raspberry Pi 5</span></div><ArrowRight/><div className="pipeline-node"><CircleDot/><small>04 / TARGET</small><b>Pan / Tilt</b><span>{tr("Correção de offset","Offset correction","Corrección de offset")}</span></div><ArrowRight/><div className="pipeline-node safe"><ShieldCheck/><small>05 / SAFETY</small><b>Interlocks</b><span>{tr("Autoriza a bomba","Authorizes pump","Autoriza la bomba")}</span></div></div>
      <div className="architecture-grid"><article><div className="arch-head"><Cpu/><span><b>Raspberry Pi 5 · 8 GB</b><small>Ubuntu Server 24.04 + PREEMPT_RT</small></span></div><div className="arch-groups"><div><small>ROS 2 JAZZY / NATIVE</small><span>slam_toolbox</span><span>Nav2</span><span>ros2_control</span><span>robot_localization</span><span>{tr("Nó de segurança","Safety node","Nodo de seguridad")}</span></div><div><small>DOCKER COMPOSE</small><span>ONNX Runtime</span><span>Mosquitto</span><span>MediaMTX</span><span>API</span></div></div></article><article><div className="arch-head"><Bot/><span><b>{tr("Máquina de estados","State machine","Máquina de estados")}</b><small>{tr("Modos oficiais","Official modes","Modos oficiales")}</small></span></div><div className="state-flow"><span>MANUAL</span><ArrowRight/><span>AUTÔNOMO</span><ArrowRight/><span>COMBATE</span></div><div className="state-alt"><span>TESTE</span><span>AVANÇO</span><span>AUTOPROTEÇÃO</span><span>EMERGÊNCIA</span></div><p className="diagram-note">{tr("Fluxo ilustrativo; regras exatas ainda serão confirmadas.","Illustrative flow; exact rules remain pending confirmation.","Flujo ilustrativo; las reglas exactas aún deben confirmarse.")}</p></article></div>
      <div className="safety-strip"><ShieldCheck/><div><b>{tr("IA não decide segurança sozinha","AI never decides safety alone","La IA no decide la seguridad sola")}</b><span>{tr("Água baixa, tombamento, obstáculo, torre elevada, painel desconectado ou perda de conexão podem bloquear atuadores e levar o robô ao modo seguro.","Low water, rollover, obstacle, raised turret, disconnected panel or lost connection can block actuators and move the robot to a safe state.","Agua baja, vuelco, obstáculo, torre elevada, panel desconectado o pérdida de conexión pueden bloquear actuadores y llevar el robot a modo seguro.")}</span></div></div>
    </section>

    <section className="gallery-section" id="galeria"><SectionTitle eyebrow={tr("Galeria técnica","Technical gallery","Galería técnica")} title={tr("Evidência, não decoração.","Evidence, not decoration.","Evidencia, no decoración.")} body={tr("Registros, diagramas e desenhos técnicos originais organizados por versão.","Original records, diagrams and technical drawings organized by version.","Registros, diagramas y dibujos técnicos originales organizados por versión.")}/><div className="gallery-toolbar">{(["all","v1","v2","v3"] as const).map(item=><button key={item} aria-pressed={galleryFilter===item} onClick={()=>setGalleryFilter(item)}>{item==="all"?tr("Todos","All","Todos"):item.toUpperCase()}</button>)}</div><div className="gallery-grid">{filteredGallery.map(item=><button className="gallery-card" key={item.src} onClick={()=>setSelectedImage(item)}><span className="gallery-image"><Image src={item.src} alt={item.title} fill sizes="(max-width:700px) 100vw,33vw"/><span className="zoom"><ZoomIn/></span></span><span className="gallery-caption"><small>{item.version.toUpperCase()} / {item.category}</small><b>{item.title}</b></span></button>)}</div></section>

    <section className="timeline-section" id="trajetoria"><SectionTitle eyebrow={tr("Trajetória","Journey","Trayectoria")} title={tr("Do laboratório para o público.","From the lab to the public.","Del laboratorio al público.")}/><div className="timeline">{timeline.map(([date,event,ver],i)=><div className="timeline-item" key={`${date}-${event}`}><div className="timeline-marker"><span>{i+1}</span></div><time>{date}</time><div><b>{event}</b><span className={`mini-version ${ver.toLowerCase()}`}>{ver}</span></div></div>)}</div><div className="media-links"><a href="https://youtu.be/_52R-JM0lVI" target="_blank" rel="noreferrer">Record Paulista <ExternalLink/></a><a href="https://youtu.be/Wk1t5fGeSlg" target="_blank" rel="noreferrer">Balanço Geral <ExternalLink/></a><a href="https://youtu.be/KF0IwnIyTP4" target="_blank" rel="noreferrer">{tr("Testes iniciais","Initial tests","Pruebas iniciales")} <ExternalLink/></a></div></section>

    <section className="team-section" id="equipe"><SectionTitle eyebrow={tr("Equipe","Team","Equipo")} title={tr("Engenharia feita em conjunto.","Engineering built together.","Ingeniería construida en equipo.")}/><div className="team-grid"><article><span>V2 · ETEC</span><h3>Matheus Gabriel Fernandes Angelo</h3><h3>Samuel Jesus Gonzaga do Nascimento</h3><h3>Weslley Ribeiro dos Santos</h3><h3>Yago Yuji Hamazaki Lorenço</h3><p><b>{tr("Orientador","Advisor","Orientador")}:</b> Prof. Luis Felipe Grael Tinos</p></article><article><span>V3 · FATEC</span><h3>Bruno Daniel Silva Deanin</h3><h3>Cauã Fernandes Jorge</h3><h3>Heitor Jorge de Moraes Neto</h3><h3>Ian Bianchi de Marche</h3><h3>Yago Yuji Hamazaki Lorenço</h3></article></div></section>

    <section className="docs-section"><div><p className="eyebrow">OPEN DOCUMENTATION</p><h2>{tr("Fontes do projeto","Project sources","Fuentes del proyecto")}</h2><p>{tr("O conteúdo foi cruzado com documentação técnica e registros da equipe.","Content was cross-checked against technical documentation and team records.","El contenido fue contrastado con documentación técnica y registros del equipo.")}</p></div><div className="doc-links"><a href="https://drive.google.com/file/d/1g-VYx57LBQX2l1jjWF_FWR9Qs9jsa7lL/view" target="_blank" rel="noreferrer"><span><b>TCC HydroBot V2</b><small>PDF · 2025</small></span><ExternalLink/></a><a href="https://drive.google.com/file/d/1pMhLYiifPnL_NnEQex6v8ombj0InppYx/view" target="_blank" rel="noreferrer"><span><b>{tr("Desenho técnico HydroBot V3","HydroBot V3 technical drawing","Dibujo técnico HydroBot V3")}</b><small>PDF · 9 {tr("pranchas A3","A3 sheets","láminas A3")} · 2026</small></span><ExternalLink/></a><a href="https://docs.google.com/document/d/1PrjU17UCwXa_Zs4jDp0HUhQhbB1TfeOE-qlFdG2HndQ/edit" target="_blank" rel="noreferrer"><span><b>{tr("Documentação V3 / PI1","V3 / PI1 documentation","Documentación V3 / PI1")}</b><small>Google Docs · 2026</small></span><ExternalLink/></a></div></section>

    <footer><div className="footer-brand"><Image src="/assets/hydrobot-logo.png" alt="HydroBot" width={54} height={54}/><div><b>HYDROBOT</b><span>{tr("Evolução documentada. Engenharia responsável.","Documented evolution. Responsible engineering.","Evolución documentada. Ingeniería responsable.")}</span></div></div><div className="footer-links"><a href="mailto:tccantiincendio@gmail.com"><Mail/> tccantiincendio@gmail.com</a><a href="https://instagram.com/hydro.bot" target="_blank" rel="noreferrer"><Camera/> @hydro.bot</a></div><p>© 2024—2026 HydroBot Team</p></footer>

    <Sheet><SheetTrigger asChild><button className="chat-trigger"><MessageCircle/><span>{tr("Pergunte ao HydroBot","Ask HydroBot","Pregunta al HydroBot")}</span></button></SheetTrigger><SheetContent className="chat-sheet"><SheetHeader><SheetTitle className="chat-title"><Bot/> HydroBot Q&A</SheetTitle><SheetDescription>{tr("Respostas baseadas na documentação do projeto.","Answers based on project documentation.","Respuestas basadas en la documentación del proyecto.")}</SheetDescription></SheetHeader><div className="chat-messages"><div className="message bot">{tr("Pergunte sobre versões, componentes, IA, segurança ou trajetória.","Ask about versions, components, AI, safety or the journey.","Pregunta sobre versiones, componentes, IA, seguridad o trayectoria.")}</div>{messages.map((m,i)=><div className={`message ${m.role}`} key={`${m.role}-${i}`}>{m.text}</div>)}</div><form className="chat-form" onSubmit={sendQuestion}><textarea value={question} maxLength={1000} onChange={e=>setQuestion(e.target.value)} placeholder={tr("Como funciona a IA da V3?","How does V3 AI work?","¿Cómo funciona la IA de la V3?")}/><button disabled={!question.trim()||sending} type="submit">{tr("Enviar","Send","Enviar")} <ArrowRight/></button><small>{tr("A pergunta é registrada para melhorar o conteúdo.","The question is recorded to improve the content.","La pregunta se registra para mejorar el contenido.")}</small></form></SheetContent></Sheet>
    <Dialog open={!!selectedImage} onOpenChange={open=>!open&&setSelectedImage(null)}><DialogContent className="image-dialog"><DialogHeader><DialogTitle>{selectedImage?.title}</DialogTitle><DialogDescription>{selectedImage?.detail}</DialogDescription></DialogHeader>{selectedImage&&<div className="dialog-image"><Image src={selectedImage.src} alt={selectedImage.title} fill sizes="90vw"/></div>}</DialogContent></Dialog>
  </main>;
}
